import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {handleCoachMarket} from '../coach-market.js';

function fixture(){
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');
 for(const file of ['schema.sql','migrations/001-runtime.sql','migrations/003-club-access.sql','migrations/011-coach-marketplace.sql','migrations/012-athlete-workouts-and-intake.sql'])sql.exec(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'));
 sql.exec(`INSERT INTO users(id,phone,full_name,role) VALUES ('support','09120000000','Support','admin'),('athlete','09120000001','Athlete','athlete'),('athlete2','09120000002','Athlete Other','athlete'),('coach','09120000003','Coach','coach'),('coach2','09120000004','Coach Other','coach'),('manager',NULL,'Manager','manager'),('manager2',NULL,'Manager Other','manager');
 INSERT INTO clubs(id,name,manager_name,manager_user_id,created_by) VALUES ('club','Club','Manager','manager','support'),('club2','Club2','Manager Other','manager2','support');
 INSERT INTO account_access(user_id,role,club_id,state) VALUES ('support','support',NULL,'approved'),('athlete','athlete','club','approved'),('athlete2','athlete','club2','approved'),('coach','coach','club','approved'),('coach2','coach','club2','approved'),('manager','manager','club','approved'),('manager2','manager','club2','approved');
 INSERT INTO coach_offerings(coach_id,workout_enabled,nutrition_enabled,in_person_enabled,workout_packages_json,in_person_packages_json) VALUES ('coach',1,1,1,'[{"id":"basic","name":"Basic","price":1000,"description":"starter"}]','[{"id":"pt","name":"PT","price":2000,"description":"in person"}]'),('coach2',1,0,0,'[]','[]');`);
 const DB={prepare(q){return {args:[],bind(...a){this.args=a;return this},first(){return sql.prepare(q).get(...this.args)||null},all(){return{results:sql.prepare(q).all(...this.args)}},run(){return{meta:{changes:Number(sql.prepare(q).run(...this.args).changes)}}}}},batch(items){sql.exec('BEGIN');try{const x=items.map(i=>i.run());sql.exec('COMMIT');return x}catch(e){sql.exec('ROLLBACK');throw e}}};
 const env={DB},users=id=>{const u=sql.prepare('SELECT u.*,a.role AS effective_role,a.state AS access_state,a.club_id FROM users u JOIN account_access a ON a.user_id=u.id WHERE u.id=?').get(id);return u};
 async function call(path,{who='coach',body,method=body===undefined?'GET':'POST'}={}){const req=new Request('https://test.invalid'+path,{method,body:body===undefined?undefined:JSON.stringify(body)}),response=(v,status=200)=>new Response(JSON.stringify(v),{status});try{const r=await handleCoachMarket(req,env,{path:new URL(req.url).pathname,headers:{},response,errorResponse:(error,status)=>response({error},status),jsonBody:r=>r.json(),currentUser:()=>users(who),hasRole:(u,...roles)=>roles.includes(u.effective_role),makeId:p=>p+'_'+crypto.randomUUID()});return{status:r.status,...await r.json()}}catch(e){if(!e.status)throw e;return{status:e.status,error:e.message}}}
 return{sql,call};
}
test('coach offer switches and packages validate and save atomically',async()=>{const f=fixture();assert.equal((await f.call('/api/coach-market/offers')).status,200);assert.equal((await f.call('/api/coach-market/offers',{who:'athlete'})).status,403);const bad=await f.call('/api/coach-market/offers',{method:'PATCH',body:{workoutEnabled:true,nutritionEnabled:true,inPersonEnabled:false,workoutPackages:[],inPersonPackages:[]}});assert.equal(bad.error,'workout_package_required');const saved=await f.call('/api/coach-market/offers',{method:'PATCH',body:{workoutEnabled:true,nutritionEnabled:false,inPersonEnabled:false,workoutPackages:[{id:'p',name:'Special',price:9000,description:'plan'}],inPersonPackages:[],specialty:'Strength',bio:'About coach',heroImage:null}});assert.equal(saved.ok,true);assert.equal((await f.call('/api/coach-market/offers')).offerings.workoutPackages[0].name,'Special')});
test('directory/profile exposes only active approved coaches in current club',async()=>{const f=fixture();let data=await f.call('/api/coach-market/coaches',{who:'athlete'});assert.equal(data.coaches.length,1);assert.equal(data.coaches[0].id,'coach');assert.equal((await f.call('/api/coach-market/coaches/coach',{who:'athlete'})).coach.name,'Coach');assert.equal((await f.call('/api/coach-market/coaches/coach2',{who:'athlete'})).status,404);assert.equal((await f.call('/api/coach-market/coaches',{who:'coach'})).status,403)});
test('workout requests require intake and expose it only to the selected coach and club staff',async()=>{const f=fixture(),key=crypto.randomUUID(),photo='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jM1sAAAAASUVORK5CYII=',body={coachId:'coach',kind:'workout',packageId:'basic',requestKey:key,notes:'optional notes',heightCm:170,weightKg:64.5,goal:'افزایش قدرت',photoData:photo};
 const missing=await f.call('/api/coach-market/requests',{who:'athlete',body:{coachId:'coach',kind:'workout',packageId:'basic',requestKey:crypto.randomUUID()}});assert.equal(missing.error,'workout_intake_required');
 const created=await f.call('/api/coach-market/requests',{who:'athlete',body});assert.equal(created.status,201);assert.equal((await f.call('/api/coach-market/requests',{who:'athlete',body})).request.id,created.request.id);const coachList=(await f.call('/api/coach-market/requests',{who:'coach'})).requests;assert.equal(coachList[0].package_price,1000);assert.equal(coachList[0].height_cm,170);assert.equal(coachList[0].weight_kg,64.5);assert.equal(coachList[0].goal,'افزایش قدرت');assert.equal(coachList[0].photo_data,photo);assert.equal((await f.call('/api/coach-market/requests',{who:'athlete2'})).requests.length,0);assert.equal((await f.call('/api/coach-market/requests/'+created.request.id,{who:'coach2',method:'PATCH',body:{status:'approved'}})).status,404);const approved=await f.call('/api/coach-market/requests/'+created.request.id,{who:'coach',method:'PATCH',body:{status:'approved'}});assert.equal(approved.status,'approved');assert.equal((await f.call('/api/coach-market/requests',{who:'manager'})).requests[0].status,'approved');assert.equal((await f.call('/api/coach-market/requests',{who:'manager2'})).requests.length,0);assert.equal(f.sql.prepare("SELECT COUNT(*) AS n FROM audit_logs WHERE action LIKE 'coach_request_%'").get().n,2)});
test('nutrition request has no price/package and disabled offerings cannot accept it',async()=>{const f=fixture(),result=await f.call('/api/coach-market/requests',{who:'athlete',body:{coachId:'coach',kind:'nutrition',requestKey:crypto.randomUUID()}});assert.equal(result.status,201);assert.equal(f.sql.prepare('SELECT package_price FROM coach_service_requests WHERE id=?').get(result.request.id).package_price,null);assert.equal((await f.call('/api/coach-market/requests',{who:'athlete2',body:{coachId:'coach2',kind:'nutrition',requestKey:crypto.randomUUID()}})).error,'offering_disabled')});
