import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const root=fs.existsSync(new URL('../../current/club-attendance.html',import.meta.url))?new URL('../../current/',import.meta.url):new URL('../../',import.meta.url),code=fs.readFileSync(new URL('club-attendance.js',root),'utf8');
class Element{constructor(tag='div',text=''){this.tag=tag;this.textContent=text;this.children=[];this.value='';this.hidden=true;this.disabled=false;}append(...n){this.children.push(...n)}replaceChildren(...n){this.children=n;if(this.tag==='select'&&n.length)this.value=n[0].value}focus(){}scrollIntoView(){}}
const flush=async()=>{for(let i=0;i<5;i++)await new Promise(setImmediate)};
function setup(role='support',failure=false){
 const html=fs.readFileSync(new URL('club-attendance.html',root),'utf8'),nodes=Object.fromEntries([...html.matchAll(/<(\w+)[^>]*\bid="([^"]+)"/g)].map(m=>[m[2],new Element(m[1])])),events={},calls=[];
 let confirmed=false;
 const request=async(path,options={})=>{calls.push({path,options});if(failure)throw {status:503,message:'mg_bridge_disabled'};if(path.endsWith('/mine'))return {trials:[],registrations:[]};if(path.endsWith('/stations'))return {isSupport:role==='support',stations:[{id:'s1',serial:'DEMO',last_seen:new Date().toISOString(),device_status:'connected',paired:1}]};if(path.endsWith('/events'))return {events:[{id:'e1',member_id:'439',occurred_at:new Date().toISOString(),state:confirmed?'approved':'pending',phone:'TEST',full_name:'<img onerror=bad>'}]};if(path.endsWith('/members'))return {members:[]};if(path==='/api/clubs')return {clubs:[{id:'c1',name:'Test'}]};if(path.endsWith('/review')){confirmed=true;return {ok:true}}return {ok:true}};
 const window={addEventListener:(name,fn)=>events[name]=fn};vm.runInNewContext(code,{window,MGCurrentUser:{role},MGApi:{request},document:{getElementById:id=>nodes[id],createElement:tag=>new Element(tag)},Date,AbortSignal,Option:function(t,v){const n=new Element('option',t);n.value=v;return n},confirm:()=>true});return {nodes,events,calls};
}
test('console waits for authentication and has no automatic writes',async()=>{const f=setup();assert.equal(f.calls.length,0);f.events['mg:access-ready']();await flush();assert.ok(f.calls.length>0);assert.equal(f.calls.filter(c=>c.options.method==='POST').length,0);assert.equal(f.nodes.staff.hidden,false);assert.equal(f.nodes.setup.hidden,false)});
test('approve is wired to the scoped API and becomes approved; button recovers',async()=>{const f=setup();f.events['mg:access-ready']();await flush();const row=f.nodes.events.children[0].children[1];assert.equal(row.children[0].textContent,'<img onerror=bad> / 439');const approve=row.children[3].children[0];await approve.onclick();await flush();const sent=f.calls.find(c=>c.path.endsWith('/review'));assert.equal(sent.options.body.confirmedAdmission,true);assert.equal(sent.options.body.eventId,'e1');assert.equal(approve.disabled,false);assert.equal(f.nodes.events.children[0].children[1].children[2].textContent,'تأیید شده')});
test('disabled server message is not overwritten with false success',async()=>{const f=setup('support',true);f.events['mg:access-ready']();await flush();assert.match(f.nodes.message.textContent,/هنوز روی سرور فعال نشده/);assert.equal(f.nodes.staff.hidden,true)});
test('athlete sees only own data and does not request staff endpoints',async()=>{const f=setup('athlete');f.events['mg:access-ready']();await flush();assert.deepEqual(f.calls.map(c=>c.path),['/api/mg-bridge/mine']);assert.equal(f.nodes.staff.hidden,true)});
test('page private, responsive and no unsafe HTML insertion',()=>{const html=fs.readFileSync(new URL('club-attendance.html',root),'utf8');assert.match(html,/noindex/);assert.match(html,/width=device-width/);assert.match(html,/mg-access-cloak/);assert.ok(!code.includes('innerHTML'));assert.match(html,/downloads\/MG-Bridge-Web-20261005.zip/)});
