import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {handleMgBridge,normalizeBridgeEvent,privateAddress} from '../mg-bridge.js';
const hash=async x=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(x))).toString('hex');
const wall=x=>new Date(x+210*60000).toISOString().slice(0,19);
function fixture(){
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');
 for(const f of ['schema.sql','migrations/001-runtime.sql','migrations/003-club-access.sql','migrations/004-attendance-pilot.sql','migrations/007-mg-bridge.sql','migrations/018-cash-memberships.sql'])sql.exec(fs.readFileSync(new URL('../'+f,import.meta.url),'utf8'));
 sql.exec(`INSERT INTO users(id,phone,role) VALUES ('support','09120000000','admin'),('athlete','09120000001','athlete'),('other','09120000002','athlete'),('manager',NULL,'manager'),('manager2',NULL,'manager'),('secretary','09120000003','athlete');
 INSERT INTO clubs(id,name,manager_name,manager_user_id,created_by) VALUES ('club','MG','M','manager','support'),('club2','Other','M2','manager2','support');
 INSERT INTO account_access(user_id,role,club_id,state) VALUES ('support','support',NULL,'approved'),('athlete','athlete','club','approved'),('other','athlete','club2','approved'),('manager','manager','club','approved'),('manager2','manager','club2','approved'),('secretary','secretary','club','approved');`);
 const db={prepare(q){return {args:[],bind(...v){this.args=v;return this},first(){return sql.prepare(q).get(...this.args)||null},all(){return {results:sql.prepare(q).all(...this.args)}},run(){return {meta:{changes:Number(sql.prepare(q).run(...this.args).changes)}}}}},batch(items){sql.exec('BEGIN');try{const r=items.map(s=>s.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
 const user=id=>sql.prepare('SELECT u.*,a.role AS effective_role,a.state AS access_state FROM users u JOIN account_access a ON a.user_id=u.id WHERE u.id=?').get(id);
 const env={DB:db,MG_BRIDGE_ENABLED:'true'};
 async function call(p,{who='support',body,secret}={}){
  const req=new Request('https://test.invalid/api/mg-bridge/'+p,{method:body===undefined?'GET':'POST',headers:secret?{authorization:'Bearer '+secret}:{},body:body===undefined?undefined:JSON.stringify(body)}),response=(x,s=200)=>new Response(JSON.stringify(x),{status:s});
  try{const r=await handleMgBridge(req,env,{path:new URL(req.url).pathname,response,errorResponse:(error,s)=>response({error},s),headers:{},jsonBody:r=>r.json(),hash,currentUser:()=>user(who),userById:(_,id)=>user(id),hasRole:(u,...rs)=>!!u&&rs.includes(u.effective_role),makeId:p=>p+'_'+crypto.randomUUID(),normalizePhone:x=>x});return {status:r.status,...await r.json()}}catch(e){if(!e.status)throw e;return {status:e.status,error:e.message}}
 }
 return {sql,call,env};
}
async function ready(){const f=fixture(),secret='a'.repeat(64),code=(await hash(secret)).slice(0,16).toUpperCase();const r=await f.call('pair',{body:{code,clubId:'club',serial:'DEV1',address:'192.168.1.201'}});assert.equal(r.status,201);const id=r.id;
 // Deterministic timestamp window for fake device observations only.
 f.sql.prepare('UPDATE mg_bridges SET capture_since=?').run(new Date(Date.now()-60000).toISOString());
 const sync=body=>f.call('agent/sync',{secret,body:{events:[],deviceStatus:'connected',...body}});assert.equal((await sync()).status,200);
 const event=(memberId='439',offset=0)=>({clientId:'test'+offset,memberId,wallTime:wall(Date.now()+offset),verify:15,punch:0,work:0});
 return {...f,id,secret,code,sync,event};}
test('bridge defaults off and only approved staff see console',async()=>{const f=fixture();assert.equal((await f.call('stations',{who:'athlete'})).status,403);assert.equal((await f.call('stations',{who:'missing'})).status,401);f.env.MG_BRIDGE_ENABLED='false';f.env.DB=null;assert.equal((await f.call('stations')).status,503)});
test('pairing is support-only and accepts only private literal IPv4',async()=>{const f=fixture();const b={code:'A'.repeat(16),clubId:'club',serial:'DEV1',address:'192.168.1.201'};assert.equal((await f.call('pair',{who:'manager',body:b})).status,403);assert.equal((await f.call('pair',{body:{...b,address:'8.8.8.8'}})).status,400);assert.equal(privateAddress('127.0.0.1'),false);assert.equal(privateAddress('192.168.1.999'),false);assert.equal(privateAddress('10.1.1.2'),true)});
test('secret is hashed; other token and expired pairing cannot poll',async()=>{const f=await ready();assert.notEqual(f.sql.prepare('SELECT token_hash FROM mg_bridges').get().token_hash,f.secret);assert.equal((await f.call('agent/sync',{secret:'b'.repeat(64),body:{events:[]}})).status,401);f.sql.exec("UPDATE mg_bridges SET token_hash=NULL,pairing_expires='2000-01-01'");assert.equal((await f.sync()).status,401)});
test('revocation and inactive issuer stop agent; another club cannot see station',async()=>{const f=await ready();assert.equal((await f.call('stations',{who:'manager2'})).stations.length,0);assert.equal((await f.call('stations/'+f.id+'/events',{who:'manager2'})).status,404);f.sql.exec("UPDATE users SET status='blocked' WHERE id='support'");assert.equal((await f.sync()).status,403);f.sql.exec("UPDATE users SET status='active' WHERE id='support'");await f.call('stations/'+f.id+'/revoke',{body:{}});assert.equal((await f.sync()).status,401)});
test('history and invalid calendar never reach ledger; replay stores once',async()=>{const f=await ready(),event=f.event();for(let i=0;i<2;i++)assert.equal((await f.sync({events:[event]})).receipts[0].status,'stored');assert.equal(f.sql.prepare('SELECT count(*) n FROM mg_bridge_events').get().n,1);for(const stamp of ['2020-01-01T00:00:00','2026-02-30T12:00:00','2099-01-01T00:00:00'])assert.equal((await f.sync({events:[{...event,wallTime:stamp}]})).receipts[0].status,'rejected');assert.equal(f.sql.prepare('SELECT count(*) n FROM mg_bridge_visits').get().n,0)});
test('member mapping needs a fresh observation, explicit attestation and unique ownership',async()=>{const f=await ready(),p='stations/'+f.id+'/map',body={phone:'09120000001',memberId:'439',confirmed:true};assert.equal((await f.call(p,{body})).error,'fresh_scan_required');await f.sync({events:[f.event()]});assert.equal((await f.call(p,{body:{...body,confirmed:false}})).status,400);assert.equal((await f.call(p,{who:'secretary',body})).status,200);assert.equal((await f.call(p,{body})).duplicate,true);assert.equal((await f.call(p,{body:{...body,phone:'09120000002'}})).error,'member_already_mapped')});
test('trial only for athlete; requests idempotent; no payments generated',async()=>{const f=await ready();await f.sync({events:[f.event()]});await f.call('stations/'+f.id+'/map',{body:{phone:'09120000001',memberId:'439',confirmed:true}});const path='stations/'+f.id+'/trial';assert.equal((await f.call(path,{who:'manager',body:{memberId:'439'}})).status,403);for(let i=0;i<2;i++)assert.equal((await f.call(path,{body:{memberId:'439'}})).status,200);assert.equal(f.sql.prepare('SELECT count(*) n FROM mg_bridge_trials').get().n,1);assert.equal(f.sql.prepare('SELECT count(*) n FROM payments').get().n,0)});
test('review charges once per Tehran day; duplicate/rejected observation never charges twice',async()=>{const f=await ready();const sync=await f.sync({events:[f.event()]});await f.call('stations/'+f.id+'/map',{body:{phone:'09120000001',memberId:'439',confirmed:true}});await f.call('stations/'+f.id+'/trial',{body:{memberId:'439'}});f.sql.prepare('UPDATE mg_bridge_trials SET starts_at=?').run(new Date(Date.now()-60000).toISOString());const p='stations/'+f.id+'/review',body={eventId:sync.receipts[0].id,decision:'approve',confirmedAdmission:true};assert.equal((await f.call(p,{body:{...body,confirmedAdmission:false}})).status,400);for(let i=0;i<2;i++)assert.equal((await f.call(p,{who:'secretary',body})).status,200);const next=await f.sync({events:[f.event('439',1000)]});assert.equal((await f.call(p,{body:{...body,eventId:next.receipts[0].id}})).status,200);assert.equal(f.sql.prepare('SELECT count(*) n FROM mg_bridge_visits').get().n,1);assert.equal((await f.call('mine',{who:'athlete'})).trials[0].used,1)});
test('cash membership visits decrement the approved package and stop at its session limit',async()=>{const f=await ready();f.sql.prepare('UPDATE mg_bridges SET capture_since=?').run(new Date(Date.now()-3*86400000).toISOString());const first=await f.sync({events:[f.event()]});await f.call('stations/'+f.id+'/map',{body:{phone:'09120000001',memberId:'439',confirmed:true}});const starts=new Date(Date.now()-3*86400000).toISOString(),expires=new Date(Date.now()+30*86400000).toISOString();f.sql.prepare("INSERT INTO orders(id,user_id,order_type,item_id,amount,status,payment_method) VALUES('order_cash','athlete','membership','mg_basic_12_30',35000000,'paid','cash')").run();f.sql.prepare("INSERT INTO memberships(id,user_id,club_id,plan_id,order_id,starts_at,expires_at,sessions_total) VALUES('membership_cash','athlete','club','mg_basic_12_30','order_cash',?,?,1)").run(starts,expires);const path='stations/'+f.id+'/review',body={eventId:first.receipts[0].id,decision:'approve',confirmedAdmission:true};assert.equal((await f.call(path,{who:'secretary',body})).status,200);assert.equal(f.sql.prepare('SELECT count(*) n FROM membership_visits').get().n,1);const snapshot=await f.call('stations/'+f.id+'/members',{who:'manager'});assert.equal(snapshot.members[0].membership.sessions_remaining,0);const repeated=await f.sync({events:[f.event('439',-86400000)]});assert.equal((await f.call(path,{who:'secretary',body:{...body,eventId:repeated.receipts[0].id}})).error,'sessions_exhausted_or_conflict');assert.equal(f.sql.prepare("SELECT state FROM mg_bridge_events WHERE id=?").get(repeated.receipts[0].id).state,'pending')});
test('exhausted plan rolls back approval; blocked user cannot be charged',async()=>{const f=await ready();const r=await f.sync({events:[f.event()]});await f.call('stations/'+f.id+'/map',{body:{phone:'09120000001',memberId:'439',confirmed:true}});await f.call('stations/'+f.id+'/trial',{body:{memberId:'439'}});const p='stations/'+f.id+'/review',body={eventId:r.receipts[0].id,decision:'approve',confirmedAdmission:true};assert.equal((await f.call(p,{body})).error,'no_valid_trial');assert.equal(f.sql.prepare('SELECT state FROM mg_bridge_events').get().state,'pending');f.sql.exec("UPDATE users SET status='blocked' WHERE id='athlete'");assert.equal((await f.call(p,{body})).error,'member_not_active')});
test('server normalizer preserves member identity and raw direction without guessing',()=>{const b={capture_since:'2000-01-01'},e={memberId:'00439',wallTime:wall(Date.now()),verify:15,punch:0,work:0};const n=normalizeBridgeEvent(e,b);assert.equal(n.memberId,'00439');assert.equal(n.raw,'[15,0,0]');assert.throws(()=>normalizeBridgeEvent({...e,verify:-1},b))});
test('31st distinct day is rejected transactionally and rejection never consumes',async()=>{
 const f=await ready(),r=await f.sync({events:[f.event()]});await f.call('stations/'+f.id+'/map',{body:{phone:'09120000001',memberId:'439',confirmed:true}});await f.call('stations/'+f.id+'/trial',{body:{memberId:'439'}});
 f.sql.prepare('UPDATE mg_bridge_trials SET starts_at=?').run(new Date(Date.now()-32*86400000).toISOString());const trial=f.sql.prepare('SELECT id FROM mg_bridge_trials').get().id;
 for(let i=1;i<=30;i++){const at=new Date(Date.now()-i*86400000).toISOString(),day=wall(Date.now()-i*86400000).slice(0,10);f.sql.prepare("INSERT INTO mg_bridge_events(id,bridge_id,member_id,occurred_at,business_day,raw_json,created_at,state) VALUES (?,?,'439',?,?,'[]',?,'approved')").run('seed'+i,f.id,at,day,at);f.sql.prepare('INSERT INTO mg_bridge_visits(id,trial_id,event_id,business_day,created_at) VALUES (?,?,?,?,?)').run('v'+i,trial,'seed'+i,day,at)}
 const p='stations/'+f.id+'/review';assert.equal((await f.call(p,{body:{eventId:r.receipts[0].id,decision:'approve',confirmedAdmission:true}})).error,'sessions_exhausted_or_conflict');assert.equal(f.sql.prepare('SELECT state FROM mg_bridge_events WHERE id=?').get(r.receipts[0].id).state,'pending');
 assert.equal((await f.call(p,{body:{eventId:r.receipts[0].id,decision:'reject'}})).status,200);assert.equal(f.sql.prepare('SELECT count(*) n FROM mg_bridge_visits').get().n,30);
});
test('repair rotates credential without deleting events and same code is rejected',async()=>{const f=await ready();await f.sync({events:[f.event()]});assert.equal((await f.call('stations/'+f.id+'/repair',{body:{code:f.code}})).status,400);const secret='c'.repeat(64),code=(await hash(secret)).slice(0,16).toUpperCase();assert.equal((await f.call('stations/'+f.id+'/repair',{body:{code}})).status,200);assert.equal((await f.sync()).status,401);assert.equal((await f.call('agent/sync',{secret,body:{events:[],deviceStatus:'connected'}})).status,200);assert.equal(f.sql.prepare('SELECT count(*) n FROM mg_bridge_events').get().n,1)});
