import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {handleWorkouts,validEducationVideo} from '../workouts.js';
import {blankWorkout,validateWorkout,normalizeExerciseName,dayDuration,timerPhases,timerAt,iranWeekday,integer} from '../workout-domain.js';
const frontendRoot=fs.existsSync(new URL('../../current/workouts.js',import.meta.url))?new URL('../../current/',import.meta.url):new URL('../../',import.meta.url);
function fixture(){
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');
 for(const name of ['schema.sql','migrations/001-runtime.sql','migrations/003-club-access.sql','migrations/008-workouts.sql','migrations/009-exercise-catalog.sql'])sql.exec(fs.readFileSync(new URL('../'+name,import.meta.url),'utf8'));
 sql.exec(`INSERT INTO users(id,phone,full_name,role) VALUES ('support','09120000000','Support','admin'),('alice','09120000001','Alice','athlete'),('bob','09120000002','Bob','athlete'),('coach','09120000003','Coach','coach'),('other','09120000004','Other Coach','coach'),('manager',NULL,'Manager','manager'),('manager2',NULL,'Other Manager','manager');
 INSERT INTO clubs(id,name,manager_name,manager_user_id,created_by) VALUES ('club','Club','Manager','manager','support'),('club2','Club2','Manager2','manager2','support');
 INSERT INTO account_access(user_id,role,club_id,state) VALUES ('support','support',NULL,'approved'),('alice','athlete','club','approved'),('bob','athlete','club2','approved'),('coach','coach','club','approved'),('other','coach','club2','approved'),('manager','manager','club','approved'),('manager2','manager','club2','approved');`);
 const DB={prepare(q){return {args:[],bind(...args){assert.ok(args.length<=100);this.args=args;return this},first(){return sql.prepare(q).get(...this.args)||null},all(){return {results:sql.prepare(q).all(...this.args)}},run(){return {meta:{changes:Number(sql.prepare(q).run(...this.args).changes)}}}}},batch(items){sql.exec('BEGIN');try{const r=items.map(x=>x.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
 const env={DB,WORKOUTS_ENABLED:'true'},user=id=>sql.prepare('SELECT u.*,a.role AS effective_role,a.state AS access_state,a.club_id FROM users u JOIN account_access a ON a.user_id=u.id WHERE u.id=?').get(id);
 async function call(path,{who='coach',body,method=body===undefined?'GET':'POST'}={}){const req=new Request('https://test.invalid/api/workouts'+path,{method,body:body===undefined?undefined:JSON.stringify(body)}),response=(v,status=200)=>new Response(JSON.stringify(v),{status});try{const result=await handleWorkouts(req,env,{path:new URL(req.url).pathname,headers:{},response,errorResponse:(error,status)=>response({error},status),jsonBody:r=>r.json(),currentUser:()=>user(who),userById:(_,id)=>user(id),hasRole:(u,...roles)=>roles.includes(u.effective_role||u.role),makeId:p=>p+'_'+crypto.randomUUID(),hash:async value=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))).toString('hex'),normalizePhone:v=>v});return {status:result.status,...await result.json()}}catch(e){if(!e.status)throw e;return {status:e.status,error:e.message}}}
 const exerciseId=sql.prepare('SELECT id FROM education_exercises ORDER BY id LIMIT 1').get().id;
 const program=()=>{const p=blankWorkout();p.title='برنامه نمونه';p.days[0]={timerEnabled:true,exercises:[{exerciseId,sets:3,reps:12,workSeconds:60,setRestSeconds:30,afterSeconds:60}]};return p};
 return {sql,env,call,program,exerciseId};
}
test('all 155 supplied names imported, styles separate, migrations repeat safely',()=>{const f=fixture();assert.equal(f.sql.prepare('SELECT count(*) n FROM education_exercises').get().n,155);assert.equal(f.sql.prepare("SELECT count(*) n FROM education_categories WHERE axis='style'").get().n,4);f.sql.exec(fs.readFileSync(new URL('../migrations/009-exercise-catalog.sql',import.meta.url),'utf8'));assert.equal(f.sql.prepare('SELECT count(*) n FROM education_exercises').get().n,155)});
test('normalization covers Persian forms, half spaces and digits',()=>{assert.equal(normalizeExerciseName('پشت‌ پا كِش ۲'),normalizeExerciseName('پشت پا کش 2'));assert.equal(normalizeExerciseName('ي'),normalizeExerciseName('ی'));assert.equal(integer('۱۲',1,20),12);for(const v of ['',null,false,1.5,-1,'2e1'])assert.throws(()=>integer(v,0,100))});
test('timer includes between-set/between-exercise rests only',()=>{const day={timerEnabled:true,exercises:[{sets:3,workSeconds:60,setRestSeconds:30,afterSeconds:12},{sets:4,workSeconds:30,setRestSeconds:20,afterSeconds:60}]};assert.equal(dayDuration(day),432);const phases=timerPhases(day);assert.equal(phases.reduce((n,x)=>n+x.seconds,0),432);assert.equal(phases.at(-1).kind,'work');assert.equal(timerAt(phases,60).kind,'setRest');assert.equal(timerAt(phases,432).complete,true);assert.equal(dayDuration({...day,timerEnabled:false}),0)});
test('empty days, seven days and 20 maximum; last rest sanitized',()=>{const f=fixture(),p=f.program();assert.equal(validateWorkout(p).days[0].exercises[0].afterSeconds,0);p.days[1].exercises=Array.from({length:21},()=>({...p.days[0].exercises[0]}));assert.throws(()=>validateWorkout(p));p.days.pop();assert.throws(()=>validateWorkout(p));assert.throws(()=>validateWorkout({}));assert.equal(dayDuration(blankWorkout().days[0]),0)});
test('athlete day follows Tehran midnight',()=>{assert.equal(iranWeekday(new Date('2026-10-02T20:29:59Z')),6);assert.equal(iranWeekday(new Date('2026-10-02T20:30:00Z')),0)});
test('feature, identity, approval and role gates',async()=>{const f=fixture();f.env.WORKOUTS_ENABLED='false';assert.equal((await f.call('/catalog')).status,503);f.env.WORKOUTS_ENABLED='true';assert.equal((await f.call('/catalog',{who:'nobody'})).status,401);assert.equal((await f.call('/templates',{who:'alice'})).status,403);f.sql.exec("UPDATE account_access SET state='pending' WHERE user_id='coach'");assert.equal((await f.call('/catalog')).status,403)});
test('canonical duplicate name resolves to same exercise; athlete cannot create',async()=>{const f=fixture(),body={name:'حرکت یکتا',muscleId:'core',styleId:'strength'};const first=await f.call('/exercises',{body});const again=await f.call('/exercises',{body:{...body,name:'حرکت‌ يكتا'}});assert.equal(first.status,201);assert.equal(again.status,200);assert.equal(first.exercise.id,again.exercise.id);assert.equal((await f.call('/exercises',{who:'alice',body})).status,403);assert.equal((await f.call('/exercises',{body:{...body,muscleId:'trx'}})).status,400)});
test('private templates, optimistic revisions and idempotent create',async()=>{const f=fixture(),body={program:f.program(),requestKey:crypto.randomUUID()},a=await f.call('/templates',{body}),b=await f.call('/templates',{body});assert.equal(a.status,201);assert.equal(a.id,b.id);assert.equal((await f.call('/templates/'+a.id,{who:'other'})).status,404);body.program.title='Changed';assert.equal((await f.call('/templates',{body})).status,409);const patch={program:body.program,revision:1};assert.equal((await f.call('/templates/'+a.id,{method:'PATCH',body:patch})).revision,2);assert.equal((await f.call('/templates/'+a.id,{method:'PATCH',body:patch})).status,409)});
test('140 distinct movements fit database binding budget',async()=>{const f=fixture(),ids=f.sql.prepare('SELECT id FROM education_exercises LIMIT 140').all(),p=f.program();p.days.forEach((d,i)=>{d.timerEnabled=false;d.exercises=ids.slice(i*20,i*20+20).map(e=>({exerciseId:e.id,sets:1,reps:10}))});assert.equal((await f.call('/templates',{body:{program:p,requestKey:crypto.randomUUID()}})).status,201)});
test('sending freezes snapshot, retries one delivery/audit, manager scoped, athlete readonly',async()=>{const f=fixture(),p=f.program(),t=await f.call('/templates',{body:{program:p,requestKey:crypto.randomUUID()}}),body={revision:1,phone:'09120000001',requestKey:crypto.randomUUID()};const sent=await f.call('/templates/'+t.id+'/send',{body});assert.equal(sent.status,201);assert.equal((await f.call('/templates/'+t.id+'/send',{body})).id,sent.id);p.title='Edited';await f.call('/templates/'+t.id,{method:'PATCH',body:{revision:1,program:p}});assert.equal((await f.call('/templates/'+t.id+'/send',{body})).id,sent.id);const view=await f.call('/deliveries/'+sent.id,{who:'alice'});assert.equal(view.program.title,'برنامه نمونه');assert.equal(view.readOnly,true);assert.equal((await f.call('/deliveries/'+sent.id,{who:'bob'})).status,404);assert.equal((await f.call('/deliveries/'+sent.id,{who:'manager2'})).status,404);assert.equal((await f.call('/deliveries',{who:'manager'})).deliveries.length,1);assert.equal((await f.call('/deliveries',{who:'manager2'})).deliveries.length,0);assert.equal((await f.call('/deliveries/'+sent.id,{who:'alice',method:'PATCH',body:{}})).status,404);assert.equal(f.sql.prepare("SELECT count(*) n FROM audit_logs WHERE action='workout_sent'").get().n,1);assert.throws(()=>f.sql.exec('UPDATE workout_deliveries SET revision=20'));assert.throws(()=>f.sql.exec('DELETE FROM workout_deliveries'));await f.call('/templates/'+t.id+'/archive',{body:{}});assert.equal((await f.call('/deliveries/'+sent.id,{who:'alice'})).status,200)});
test('cross-club recipient and stale revision refused',async()=>{const f=fixture(),t=await f.call('/templates',{body:{program:f.program(),requestKey:crypto.randomUUID()}});assert.equal((await f.call('/templates/'+t.id+'/send',{body:{revision:1,phone:'09120000002',requestKey:crypto.randomUUID()}})).status,403);assert.equal((await f.call('/templates/'+t.id+'/send',{body:{revision:2,phone:'09120000001',requestKey:crypto.randomUUID()}})).status,409)});
test('many coach videos share exercise identity, external/script URLs refused',async()=>{const f=fixture(),body={title:'آموزش',url:'https://mgfitclub.ir/assets/media/test.mp4'};for(const who of ['coach','other'])assert.equal((await f.call('/exercises/'+f.exerciseId+'/videos',{who,body})).status,200);assert.equal((await f.call('/exercises/'+f.exerciseId+'/videos',{who:'alice'})).videos.length,2);for(const url of ['javascript:alert(1)','http://mgfitclub.ir/assets/media/a.mp4','https://evil.test/a.mp4','https://mgfitclub.ir/assets/media/../../secret.mp4'])assert.equal(validEducationVideo(url),false)});
test('frontend shares exact domain and protected pages have live API guard',()=>{assert.equal(fs.readFileSync(new URL('../workout-domain.js',import.meta.url),'utf8'),fs.readFileSync(new URL('workout-domain.js',frontendRoot),'utf8'));for(const name of ['coach','coach-programs','workout-view','exercise-library','workout-log']){const html=fs.readFileSync(new URL(name+'.html',frontendRoot),'utf8');assert.ok(html.includes('id="mg-access-cloak"'));assert.ok(html.includes('mg-api.js?v=20260919-access'))}});
