import {WEEK_DAYS,MEAL_TYPES,blankNutrition,validateNutrition,iranWeekday} from './workout-domain.js';
const root=document.getElementById('nutrition-root'),status=document.getElementById('nutrition-status'),mode=document.body.dataset.nutritionPage;
const $=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
const button=(text,fn,cls)=>{const b=$('button',text,cls);b.type='button';b.onclick=fn;return b};
const link=(text,href)=>{const a=$('a',text);a.href=href;return a};
const field=(label,node)=>{const l=$('label',label);l.append(node);return l};
const actions=(...nodes)=>{const d=$('div',undefined,'w-actions');d.append(...nodes);return d};
const api=(path,method='GET',body)=>MGApi.request('/api/workouts/nutrition'+path,{method,...(body===undefined?{}:{body}),signal:AbortSignal.timeout(25000)});
const sendApi=(path,method='GET',body)=>MGApi.request('/api/workouts'+path,{method,...(body===undefined?{}:{body}),signal:AbortSignal.timeout(25000)});
const key=()=>crypto.randomUUID(),normalizeError=e=>({workouts_disabled:'بخش برنامه غذایی هنوز روی سرور آماده نشده است.',revision_conflict:'این برنامه در جای دیگری تغییر کرده؛ اطلاعات فعلی را نگه دارید و دوباره بارگذاری کنید.',athlete_not_found:'حساب ورزشکار با این شماره پیدا نشد.',athlete_required:'گیرنده باید حساب ورزشکار تأییدشده داشته باشد.',coach_club_required:'عضویت مربی در باشگاه هنوز تأیید نشده است.',athlete_other_club:'این ورزشکار به باشگاه دیگری متصل است.',invalid_meal:'برای هر وعده، نوع و توضیحات را کامل کنید.',title_required:'نام برنامه را وارد کنید.'}[e?.message]||'عملیات انجام نشد؛ اتصال و دسترسی حساب را بررسی کنید.');
function report(value,error=false){status.textContent=typeof value==='string'?value:normalizeError(value);status.className=error||typeof value!=='string'?'w-error':''}
async function run(b,fn){if(b?.disabled)return;if(b)b.disabled=true;try{return await fn()}catch(e){report(e,true)}finally{if(b)b.disabled=false}}
function modal(title){const d=$('dialog'),content=$('div'),close=button('بستن',()=>d.close());d.append($('h2',title),content,close);d.addEventListener('close',()=>d.remove(),{once:true});document.body.append(d);d.showModal();return {d,content,close}}
let started=false,user,program=blankNutrition(),day=0,dirty=false,busy=false,templateId=new URLSearchParams(location.search).get('id'),revision=0,createKey=key(),lastCreateBody='',selectedProgram,deliveryLoadVersion=0;
window.addEventListener('beforeunload',e=>{if(mode==='builder'&&dirty){e.preventDefault();e.returnValue=''}});
document.addEventListener('click',e=>{if(mode!=='builder'||!dirty)return;const a=e.target.closest?.('a[href]');if(!a||e.ctrlKey||e.metaKey||a.target==='_blank')return;e.preventDefault();leave(a.href)});
function leave(href){if(busy)return;const {d,content}=modal('پیش از خروج ذخیره شود؟');content.append($('p','تغییرات برنامه غذایی هنوز ذخیره نشده‌اند.'),actions(button('ذخیره و خروج',async()=>{if(await save()){dirty=false;location.href=href}},'primary'),button('خروج بدون ذخیره',()=>{dirty=false;location.href=href}),button('ادامه ویرایش',()=>d.close())))}
function mark(){dirty=true;report('تغییرات ذخیره نشده');updateCount()}
function updateCount(){const count=document.getElementById('nutrition-count');if(count)count.textContent=program.days[day].meals.length+' از ۲۰ وعده'}
function dayTabs(onchange){const nav=$('nav',undefined,'w-days');nav.setAttribute('role','tablist');nav.setAttribute('aria-label','روزهای هفته');WEEK_DAYS.forEach((label,index)=>{const b=button(label,()=>{day=index;onchange()});b.setAttribute('role','tab');b.setAttribute('aria-selected',String(day===index));nav.append(b)});return nav}
function mealSelect(value,onchange){const select=$('select');select.className='n-meal-select';select.required=true;for(const meal of MEAL_TYPES){const o=$('option',meal.icon+'  '+meal.label);o.value=meal.id;select.append(o)}select.value=value;select.onchange=()=>onchange(select.value);return select}
function renderBuilder(){root.replaceChildren();const form=$('form'),fieldset=$('fieldset');fieldset.disabled=busy;form.append(fieldset);form.onsubmit=async e=>{e.preventDefault();await save()};
 const title=$('input');title.maxLength=140;title.required=true;title.value=program.title;title.oninput=()=>{program.title=title.value;mark()};fieldset.append(field('نام برنامه غذایی',title),dayTabs(renderBuilder));
 const data=program.days[day],head=$('div',undefined,'n-day-title');head.append($('h2','وعده‌های غذایی '+WEEK_DAYS[day]),$('span',data.meals.length+' از ۲۰ وعده','n-count'));const counter=head.querySelector?.('.n-count');if(counter)counter.id='nutrition-count';fieldset.append(head);
 if(!data.meals.length)fieldset.append($('p','برای این روز هنوز وعده‌ای ثبت نشده است.','n-empty'));
 data.meals.forEach((meal,index)=>{const card=$('section',undefined,'w-card'),type=MEAL_TYPES.find(x=>x.id===meal.type)||MEAL_TYPES[0],row=$('div',undefined,'n-meal-edit'),select=mealSelect(meal.type,value=>{meal.type=value;mark();renderBuilder()}),description=$('textarea');description.required=true;description.maxLength=3000;description.value=meal.description;description.placeholder='مثال: ۳ عدد تخم‌مرغ با نان جو';description.setAttribute('aria-label','توضیحات '+type.label);description.oninput=()=>{meal.description=description.value;mark()};const chip=$('span',type.icon+' '+type.label,'n-choice-icon');row.append(field('نوع وعده',select),field('توضیحات برنامه',description));card.append($('div',type.icon+'  '+type.label,'n-choice'),row,actions(button('حذف وعده',()=>{if(confirm('این وعده حذف شود؟')){data.meals.splice(index,1);mark();renderBuilder()}})));fieldset.append(card)});
 const add=button('＋ اضافه کردن وعده غذایی',()=>{if(data.meals.length>=20)return;data.meals.push({type:'breakfast',description:''});mark();renderBuilder()},'primary');add.disabled=data.meals.length>=20;
 const saveButton=$('button','ذخیره برنامه','primary');saveButton.type='submit';fieldset.append(actions(add,saveButton,link('فهرست برنامه‌های غذایی','coach-food.html')), $('p','نسخه‌ای که به ورزشکار ارسال شود، مستقل و فقط‌خواندنی باقی می‌ماند.','w-muted'));root.append(form);updateCount()}
async function save(){if(busy)return false;const form=root.querySelector('form');if(!form?.reportValidity())return false;let clean;try{clean=validateNutrition(program)}catch(e){report(e,true);return false}
 if(!templateId){const signature=JSON.stringify(clean);if(lastCreateBody&&lastCreateBody!==signature)createKey=key();lastCreateBody=signature}
 busy=true;const fs=root.querySelector('fieldset');if(fs)fs.disabled=true;
 try{const saved=await api('/templates'+(templateId?'/'+templateId:''),templateId?'PATCH':'POST',templateId?{program:clean,revision}:{program:clean,requestKey:createKey});templateId=saved.id;revision=saved.revision;program=saved.program;dirty=false;history.replaceState(null,'','nutrition-builder.html?id='+encodeURIComponent(templateId));report('برنامه غذایی ذخیره شد.');return true}catch(e){report(e,true);return false}finally{busy=false;renderBuilder()}}
async function library(){root.replaceChildren(actions(link('＋ ساخت برنامه غذایی','nutrition-builder.html'),link('برنامه‌های تمرینی','coach-programs.html'),link('گزارش برنامه‌های ارسال‌شده','workout-log.html')));const data=await api('/templates'),list=$('div',undefined,'w-list');root.append(list);if(!data.programs.length)list.append($('p','هنوز برنامه غذایی نساخته‌اید.'));
 for(const plan of data.programs){const card=$('article',undefined,'w-card n-template-card'),archive=button('بایگانی',async()=>{if(!confirm('برنامه بایگانی شود؟ ارسال‌های قبلی باقی می‌مانند.'))return;await run(archive,async()=>{await api('/templates/'+plan.id+'/archive','POST',{});await library()})});card.append($('h2',plan.title),$('p','آخرین ویرایش: '+new Date(plan.updated_at).toLocaleDateString('fa-IR',{timeZone:'Asia/Tehran'})+' · نسخه '+plan.revision,'w-muted'),actions(link('ویرایش','nutrition-builder.html?id='+encodeURIComponent(plan.id)),button('ارسال به ورزشکار',()=>send(plan),'primary'),archive));list.append(card)}report('برنامه‌های غذایی مربی')}
function send(plan){const {content,close}=modal('ارسال برنامه غذایی به ورزشکار'),form=$('form'),phone=$('input'),notice=$('p'),submit=$('button','تأیید ارسال','primary');phone.type='tel';phone.dir='ltr';phone.required=true;phone.placeholder='09…';form.append(field('شماره حساب ورزشکار',phone),$('p','نسخه فعلی ارسال می‌شود و در گزارش مدیر باشگاه ثبت خواهد شد.','w-muted'),submit,notice);content.append(form);let requestKey=key(),lastPhone='';form.onsubmit=async e=>{e.preventDefault();if(phone.value!==lastPhone){requestKey=key();lastPhone=phone.value}submit.disabled=true;phone.disabled=true;close.disabled=true;try{await api('/templates/'+plan.id+'/send','POST',{phone:phone.value,revision:plan.revision,requestKey});notice.textContent='برنامه غذایی ارسال شد و در گزارش مدیر ثبت شد.';submit.remove()}catch(e){notice.textContent=normalizeError(e)}finally{submit.disabled=false;phone.disabled=false;close.disabled=false}}}
function iconFor(type){return MEAL_TYPES.find(x=>x.id===type)||MEAL_TYPES[0]}
function renderMeals(container,p){container.replaceChildren();if(!p.meals.length){container.append($('p','برای این روز وعده‌ای ثبت نشده است.','n-empty'));return}for(const meal of p.meals){const info=iconFor(meal.type),card=$('article',undefined,'w-card n-meal'),icon=$('div',info.icon, 'n-icon');icon.style.backgroundColor=info.color;icon.setAttribute('aria-hidden','true');const text=$('div');text.append($('h3',info.label),$('p',meal.description,'n-desc'));card.append(icon,text);container.append(card)}}
function tehranDay(){return iranWeekday()}
async function viewer(){const params=new URLSearchParams(location.search),select=$('select'),box=$('section'),more=button('نمایش برنامه‌های بیشتر',async b=>run(b,load));select.append(new Option('یک برنامه را انتخاب کنید',''));if(params.get('id')){select.disabled=true}
 root.append(field('برنامهٔ غذایی دریافتی',select),more,box);let page=1,loading=false;
 async function open(id){if(!id)return;const version=++deliveryLoadVersion;box.replaceChildren($('p','در حال دریافت برنامه…'));try{const data=await sendApi('/deliveries/'+encodeURIComponent(id));if(version!==deliveryLoadVersion)return;selectedProgram=data;day=tehranDay();if(![...select.options].some(o=>o.value===id))select.append(new Option(data.title,id));select.value=id;box.replaceChildren($('h2',data.title),$('p','مربی: '+data.coachName+' · نسخه '+data.revision+' · فقط خواندنی','w-muted'));const days=$('div');box.append(days);const render=()=>{days.replaceChildren(dayTabs(render));const current=data.program.days[day];days.append($('h2','وعده‌های '+WEEK_DAYS[day]));renderMeals(days,current)};render()}catch(e){if(version===deliveryLoadVersion){box.replaceChildren();report(e,true)}}}
 async function load(){if(loading)return;loading=true;try{const result=await sendApi('/nutrition/deliveries?page='+page);page++;for(const item of result.deliveries)select.append(new Option(item.title+' · '+item.coach_name+' · '+new Date(item.sent_at).toLocaleDateString('fa-IR',{timeZone:'Asia/Tehran'}),item.id));more.hidden=!result.hasMore;if(page===2&&!result.deliveries.length)box.append($('p','هنوز برنامه غذایی برای شما ارسال نشده است.'))}finally{loading=false}}
 select.onchange=()=>{if(select.value)open(select.value);else{deliveryLoadVersion++;box.replaceChildren()}};await load();const id=params.get('id');if(id)await open(id);report('یک برنامه را انتخاب کنید؛ این نسخه را فقط مربی می‌تواند ویرایش کند.')}
async function init(value){if(started)return;started=true;user=value;const allowed=mode==='viewer'?['athlete','manager','support','coach']:['coach'];if(!allowed.includes(user.role)){location.replace(user.role==='athlete'?'dashboard.html':user.role==='manager'?'admin.html':user.role==='support'?'support.html':'coach-dashboard.html');return}
 const back=document.getElementById('nutrition-back');if(back&&mode==='viewer')back.href=user.role==='athlete'?'dashboard.html':user.role==='manager'?'admin.html':user.role==='support'?'support.html':'coach-dashboard.html';
 try{if(mode==='builder'){if(templateId){const saved=await api('/templates/'+encodeURIComponent(templateId));if(saved.archived)throw Error('program_archived');program=saved.program;revision=saved.revision}day=0;renderBuilder();report('روز شنبه · برنامه غذایی هفتگی')}else if(mode==='library')await library();else await viewer()}catch(e){report(e,true);root.append(button('تلاش دوباره',()=>location.reload()))}}
window.addEventListener('mg:access-ready',e=>init(e.detail));if(window.MGCurrentUser)init(window.MGCurrentUser);
