import {WEEK_DAYS,blankWorkout,validateWorkout,dayDuration,timerPhases,timerAt,iranWeekday,normalizeExerciseName} from './workout-domain.js';
const root=document.getElementById('workout-root'),status=document.getElementById('workout-status'),mode=document.body.dataset.workoutPage;
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
const btn=(text,fn,cls)=>{const e=el('button',text,cls);e.type='button';e.onclick=fn;return e};
const link=(text,href)=>{const a=el('a',text);a.href=href;return a};
const field=(text,input)=>{const l=el('label',text);l.append(input);return l};
const actions=(...items)=>{const d=el('div',undefined,'w-actions');d.append(...items);return d};
const api=(path,method='GET',body)=>MGApi.request('/api/workouts'+path,{method,...(body===undefined?{}:{body}),signal:AbortSignal.timeout(25000)});
const key=()=>crypto.randomUUID(),time=n=>{n=Math.max(0,Math.round(n||0));return [Math.floor(n/3600),Math.floor(n/60)%60,n%60].map(v=>String(v).padStart(2,'0')).join(':')};
const messages={workouts_disabled:'این بخش هنوز روی سرور فعال نشده است.',revision_conflict:'این برنامه در جای دیگری تغییر کرده است. صفحه را در تب جدید باز کنید؛ تغییرات فعلی را قبل از بازخوانی نگه دارید.',athlete_not_found:'حسابی با این شماره پیدا نشد.',athlete_required:'گیرنده باید ورزشکار تأییدشده باشد.',coach_club_required:'ابتدا عضویت مربی در باشگاه باید تأیید شود.',athlete_other_club:'این ورزشکار به باشگاه دیگری متصل است.',exercise_unavailable:'یکی از حرکات دیگر در بانک موجود نیست.',title_required:'نام برنامه را وارد کنید.',category_required:'گروه و سبک تمرین را انتخاب کنید.'};
function report(e){status.textContent=typeof e==='string'?e:(messages[e.message]||'ذخیره یا دریافت اطلاعات انجام نشد؛ ورودی‌ها، اتصال و دسترسی حساب را بررسی کنید.');status.className=typeof e==='string'?'':'w-error'}
async function run(b,fn){if(b?.disabled)return;if(b)b.disabled=true;try{return await fn()}catch(e){report(e)}finally{if(b)b.disabled=false}}
function modal(title){const d=el('dialog'),h=el('h2',title),content=el('div'),close=btn('بستن',()=>d.close());d.append(h,content,close);d.addEventListener('close',()=>d.remove(),{once:true});document.body.append(d);d.showModal();return {d,content,close}}
let user,started=false,dirty=false,busy=false,program=blankWorkout(),templateId=new URLSearchParams(location.search).get('id'),revision=0,createKey=key(),day=0,catalog,loadVersion=0,lastCreateBody='';
function mark(){dirty=true;report('تغییرات ذخیره نشده');updateSummary()}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
document.addEventListener('click',e=>{const a=e.target.closest?.('a[href]');if(mode!=='builder'||!dirty||!a||a.target==='_blank'||e.ctrlKey||e.metaKey)return;e.preventDefault();leave(a.href)});
function leave(href){if(busy)return;const {d,content}=modal('قبل از خروج ذخیره شود؟');content.append(el('p','تغییرات این برنامه هنوز ذخیره نشده‌اند.'),actions(btn('ذخیره و خروج',async()=>{if(await save()){dirty=false;location.href=href}},'primary'),btn('خروج بدون ذخیره',()=>{dirty=false;location.href=href}),btn('ادامه ویرایش',()=>d.close())))}
async function getCatalog(){if(catalog)return catalog;let page=1,all=[],data;do{data=await api('/catalog?page='+page++);all.push(...data.exercises)}while(data.hasMore);catalog={...data,exercises:all};return catalog}
function categorySelect(categories,axis,all=true){const s=el('select');if(all){const o=el('option',axis==='muscle'?'همه گروه‌ها':'همه سبک‌ها');o.value='';s.append(o)}for(const c of categories.filter(c=>c.axis===axis)){const o=el('option',c.name);o.value=c.id;s.append(o)}return s}
async function pickExercise(callback){const {content}=modal('انتخاب حرکت از بانک مشترک');content.append(el('p','در حال دریافت…'));try{await catalogUI(content,callback)}catch(e){content.replaceChildren(el('p',messages[e.message]||'دریافت بانک حرکات ممکن نشد.'));report(e)}}
async function catalogUI(host,callback){const data=await getCatalog();host.replaceChildren();const q=el('input');q.placeholder='جست‌وجوی نام فارسی یا انگلیسی';q.type='search';q.setAttribute('aria-label','جست‌وجوی حرکت');const muscle=categorySelect(data.categories,'muscle'),style=categorySelect(data.categories,'style'),results=el('div',undefined,'w-results');let limit=60;const more=btn('نمایش بیشتر',()=>{limit+=60;draw()}),count=el('p',undefined,'w-count');
 const filters=el('div',undefined,'w-fields');filters.append(field('جست‌وجو',q),field('گروه بدنی',muscle),field('سبک تمرین',style));host.append(filters,count,results,more);
 const normalize=normalizeExerciseName;
 function draw(){const search=normalize(q.value),rows=data.exercises.filter(x=>(!muscle.value||x.muscle_id===muscle.value)&&(!style.value||x.style_id===style.value)&&normalize(x.name+' '+(x.english_name||'')).includes(search));count.textContent=rows.length+' حرکت';results.replaceChildren();for(const x of rows.slice(0,limit)){const b=btn(x.name+' · '+(data.categories.find(c=>c.id===x.style_id)?.name||''),()=>{if(callback){callback(x);host.closest('dialog')?.close()}else lessons(x.exerciseId||x.id)});results.append(b)}more.hidden=rows.length<=limit;if(!rows.length)results.append(el('p','حرکتی پیدا نشد.'))}
 for(const f of [q,muscle,style])f.addEventListener('input',()=>{limit=60;draw()});draw();
 if(data.canCreate)host.append(btn('＋ افزودن حرکت جدید',()=>addMovement(async x=>{catalog=null;await catalogUI(host,callback);if(callback){callback(x);host.closest('dialog')?.close()}})));
}
async function addMovement(done){const data=await getCatalog(),{d,content,close}=modal('افزودن حرکت به بانک آموزش');const form=el('form'),name=el('input'),muscle=categorySelect(data.categories,'muscle',false),style=categorySelect(data.categories,'style',false),notice=el('p');name.required=true;name.maxLength=140;const submit=el('button','ثبت حرکت','primary');form.append(field('نام یکتای حرکت',name),field('گروه بدنی',muscle),field('سبک تمرین',style),el('p','نام‌های یکسان با شکل متفاوت ی، ک یا فاصله دوباره ثبت نمی‌شوند.','w-muted'),submit,notice);content.append(form);form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;close.disabled=true;try{const result=await api('/exercises','POST',{name:name.value,muscleId:muscle.value,styleId:style.value});await done(result.exercise);d.close();report(result.existing?'این حرکت قبلاً وجود داشت؛ همان حرکت انتخاب شد.':'حرکت به بانک مشترک اضافه شد.')}catch(e){notice.textContent=messages[e.message]||'ثبت انجام نشد؛ دوباره تلاش کنید.'}finally{submit.disabled=false;close.disabled=false}}}
async function lessons(id){const {content}=modal('آموزش حرکت');content.append(el('p','در حال دریافت…'));try{const data=await api('/exercises/'+encodeURIComponent(id)+'/videos');content.replaceChildren(el('h3',data.exercise.name));if(!data.videos.length)content.append(el('p','هنوز ویدیویی برای این حرکت منتشر نشده است.'));for(const v of data.videos){const card=el('section',undefined,'w-card'),video=el('video');video.controls=true;video.preload='none';video.playsInline=true;video.src=v.url;card.append(el('h3',v.title),el('p','مربی: '+v.coach_name),video);content.append(card)}}catch(e){content.replaceChildren(el('p','دریافت آموزش ممکن نشد.'));report(e)}}
function dayTabs(onchange){const nav=el('nav',undefined,'w-days');nav.setAttribute('aria-label','روزهای هفته');nav.setAttribute('role','tablist');WEEK_DAYS.forEach((name,i)=>{const b=btn(name,()=>{day=i;onchange()});b.setAttribute('role','tab');b.setAttribute('aria-selected',String(day===i));nav.append(b)});return nav}
function updateSummary(){const e=document.getElementById('day-duration');if(e)e.textContent='زمان خودکار روز: '+time(dayDuration(program.days[day]))}
function numberField(text,value,min,max,change){const n=el('input');n.type='number';n.inputMode='numeric';n.min=min;n.max=max;n.step=1;n.value=value;n.required=true;n.oninput=()=>{change(n.value===''?'':Number(n.value));mark()};return field(text,n)}
function renderBuilder(){root.replaceChildren();const form=el('form'),fs=el('fieldset');fs.disabled=busy;form.append(fs);form.onsubmit=async e=>{e.preventDefault();await save()};const title=el('input');title.value=program.title;title.required=true;title.maxLength=140;title.oninput=()=>{program.title=title.value;mark()};const saveButton=el('button','ذخیره برنامه','primary');fs.append(field('نام برنامه',title),dayTabs(renderBuilder));
 const current=program.days[day],toggle=el('input');toggle.type='checkbox';toggle.checked=current.timerEnabled;toggle.onchange=()=>{current.timerEnabled=toggle.checked;mark();renderBuilder()};const summary=el('div',undefined,'w-summary'),duration=el('strong');duration.id='day-duration';summary.append(field('تایمر این روز فعال باشد',toggle),duration);fs.append(summary);
 if(!current.exercises.length)fs.append(el('p','استراحت — هنوز حرکتی برای این روز انتخاب نشده است.','w-rest'));
 current.exercises.forEach((x,i)=>{const card=el('section',undefined,'w-card');card.append(el('h2',(i+1)+'. '+(x.name||'حرکت')),actions(btn('تغییر حرکت',()=>pickExercise(selected=>{x.exerciseId=selected.id;x.name=selected.name;mark();renderBuilder()})),btn('آموزش',()=>lessons(x.exerciseId))));const fields=el('div',undefined,'w-fields');fields.append(numberField('تعداد ست',x.sets,1,50,v=>x.sets=v),numberField('تکرار در هر ست',x.reps,1,1000,v=>x.reps=v));if(current.timerEnabled)fields.append(numberField('زمان هر ست (ثانیه)',x.workSeconds,1,3600,v=>x.workSeconds=v),numberField('استراحت بین ست‌ها (ثانیه)',x.setRestSeconds,0,3600,v=>x.setRestSeconds=v));card.append(fields);const up=btn('↑ بالاتر',()=>{[current.exercises[i-1],current.exercises[i]]=[x,current.exercises[i-1]];mark();renderBuilder()}),down=btn('↓ پایین‌تر',()=>{[current.exercises[i+1],current.exercises[i]]=[x,current.exercises[i+1]];mark();renderBuilder()});up.disabled=i===0;down.disabled=i===current.exercises.length-1;card.append(actions(up,down,btn('حذف حرکت',()=>{if(confirm('این حرکت از برنامه حذف شود؟')){current.exercises.splice(i,1);mark();renderBuilder()}})));fs.append(card);if(current.timerEnabled&&i<current.exercises.length-1)fs.append(numberField('استراحت تا حرکت بعدی (ثانیه)',x.afterSeconds,0,3600,v=>x.afterSeconds=v))});
 const add=btn('＋ تمرین جدید',()=>pickExercise(x=>{if(current.exercises.length>=20)return;current.exercises.push({exerciseId:x.id,name:x.name,sets:3,reps:12,workSeconds:30,setRestSeconds:30,afterSeconds:60});mark();renderBuilder()}),'primary');add.disabled=current.exercises.length>=20;fs.append(actions(add,saveButton,link('لیست برنامه‌های من','coach-programs.html')),el('p',current.exercises.length+' از ۲۰ حرکت · نسخه ارسالی به ورزشکار مستقل باقی می‌ماند.','w-muted'));root.append(form);updateSummary()}
async function save(){if(busy)return false;const form=root.querySelector('form');if(form&&!form.reportValidity())return false;let clean;try{clean=validateWorkout(program)}catch(e){report(e);return false}if(!templateId){const signature=JSON.stringify(clean);if(lastCreateBody&&lastCreateBody!==signature)createKey=key();lastCreateBody=signature}busy=true;root.querySelector('fieldset').disabled=true;try{const result=await api('/templates'+(templateId?'/'+templateId:''),templateId?'PATCH':'POST',templateId?{program:clean,revision}:{program:clean,requestKey:createKey});templateId=result.id;revision=result.revision;program=result.program;dirty=false;history.replaceState(null,'','coach.html?id='+encodeURIComponent(templateId));report('برنامه با موفقیت ذخیره شد.');return true}catch(e){report(e);return false}finally{busy=false;renderBuilder()}}
async function library(){root.replaceChildren();root.append(actions(link('＋ ساخت برنامه تمرینی','coach.html'),link('برنامه‌های ارسال‌شده','workout-log.html'),link('برنامه غذایی','coach-food.html')));const data=await api('/templates'),list=el('div',undefined,'w-list');root.append(list);if(!data.programs.length)list.append(el('p','هنوز برنامه‌ای نساخته‌اید.'));for(const p of data.programs){const card=el('article',undefined,'w-card');card.append(el('h2',p.title),el('p','نسخه '+p.revision,'w-muted'),actions(link('ویرایش','coach.html?id='+encodeURIComponent(p.id)),btn('ارسال به ورزشکار',()=>send(p),'primary'),btn('بایگانی',async e=>{if(confirm('برنامه بایگانی شود؟ نسخه‌های ارسالی حذف نمی‌شوند.'))await run(e.currentTarget,async()=>{await api('/templates/'+p.id+'/archive','POST',{});await library()})})));list.append(card)}report('برنامه‌های ذخیره‌شده در حساب مربی')}
function send(p){const {content}=modal('ارسال نسخه '+p.revision+' از '+p.title),form=el('form'),phone=el('input'),notice=el('p'),submit=el('button','تأیید ارسال','primary');let sendKey=key(),lastPhone='';phone.type='tel';phone.dir='ltr';phone.required=true;phone.placeholder='09…';form.append(field('شماره حساب ورزشکار',phone),el('p','نسخه فعلی برای ورزشکار ثبت می‌شود و در گزارش مدیر باشگاه می‌ماند.','w-muted'),submit,notice);content.append(form);form.onsubmit=async e=>{e.preventDefault();if(phone.value!==lastPhone){sendKey=key();lastPhone=phone.value}submit.disabled=true;phone.disabled=true;try{await api('/templates/'+p.id+'/send','POST',{phone:phone.value,revision:p.revision,requestKey:sendKey});notice.textContent='برنامه با موفقیت به ورزشکار ارسال شد.';submit.remove()}catch(e){notice.textContent=messages[e.message]||'ارسال تأیید نشد؛ با همین دکمه دوباره تلاش کنید.'}finally{submit.disabled=false;phone.disabled=false}}}
let elapsed=0,anchor=0,running=false,phases=[],tickHandle,viewProgram;
function stopTimer(){running=false;elapsed=0;clearInterval(tickHandle);tickHandle=null}
function drawTimer(){const clock=document.getElementById('workout-clock');if(!clock)return;const t=timerAt(phases,elapsed+(running?(performance.now()-anchor)/1000:0));clock.textContent=t.complete?'تمرین امروز تمام شد':((t.kind==='work'?'اجرا':t.kind==='setRest'?'استراحت بین ست‌ها':'استراحت تا حرکت بعد')+' · '+(viewProgram.days[day].exercises[t.exerciseIndex]?.name||'')+' · ست '+t.set+' · '+time(t.remaining));document.querySelectorAll('[data-exercise-index]').forEach(e=>e.classList.toggle('w-active',!t.complete&&Number(e.dataset.exerciseIndex)===t.exerciseIndex));if(t.complete){running=false;clearInterval(tickHandle);document.getElementById('timer-toggle').disabled=true}}
function renderViewerDay(container){stopTimer();container.replaceChildren(dayTabs(()=>renderViewerDay(container)));const d=viewProgram.days[day];if(!d.exercises.length){container.append(el('p','امروز روز استراحت است.','w-rest'));return}if(d.timerEnabled){phases=timerPhases(d);const box=el('section',undefined,'w-card'),clock=el('p',undefined,'w-timer');clock.id='workout-clock';const toggle=btn('شروع',()=>{if(running){elapsed+=(performance.now()-anchor)/1000;running=false;toggle.textContent='ادامه';clearInterval(tickHandle)}else{anchor=performance.now();running=true;toggle.textContent='توقف موقت';tickHandle=setInterval(drawTimer,250)}drawTimer()},'primary');toggle.id='timer-toggle';box.append(el('p','زمان کل: '+time(dayDuration(d))),clock,actions(toggle,btn('از ابتدا',()=>{stopTimer();toggle.disabled=false;toggle.textContent='شروع';drawTimer()})));container.append(box)}else container.append(el('p','این روز بدون تایمر تنظیم شده است.','w-muted'));
 d.exercises.forEach((x,i)=>{const card=el('article',undefined,'w-card');card.dataset.exerciseIndex=i;card.append(el('h2',(i+1)+'. '+x.name),el('p',x.sets+' ست × '+x.reps+' تکرار'));if(d.timerEnabled)card.append(el('p','هر ست '+x.workSeconds+' ثانیه · بین ست‌ها '+x.setRestSeconds+' ثانیه'+(i<d.exercises.length-1?' · تا حرکت بعد '+x.afterSeconds+' ثانیه':''),'w-muted'));card.append(btn('آموزش حرکت',()=>lessons(x.exerciseId)));container.append(card)});if(d.timerEnabled)drawTimer()}
async function deliveries(log=false){root.replaceChildren();const select=el('select'),body=el('div'),list=el('div',undefined,'w-list'),more=btn('نمایش برنامه‌های بیشتر',()=>run(more,load));let page=1;select.append(new Option('یک برنامه را انتخاب کنید',''));if(!log)root.append(field('برنامه دریافتی',select));else root.append(list);root.append(more,body);
 async function open(id){const version=++loadVersion;stopTimer();body.replaceChildren(el('p','دریافت نسخه ارسالی…'));try{const data=await api('/deliveries/'+encodeURIComponent(id));if(version!==loadVersion)return;viewProgram=data.program;day=iranWeekday();body.replaceChildren(el('h2',data.title),el('p','مربی: '+data.coachName+' · ورزشکار: '+data.athleteName+' · نسخه '+data.revision+' · فقط خواندنی','w-muted'));const days=el('div');body.append(days);renderViewerDay(days)}catch(e){if(version===loadVersion){body.replaceChildren();report(e)}}}
 async function load(){const data=await api('/deliveries?page='+page);page++;for(const p of data.deliveries){if(log){const card=el('article',undefined,'w-card'),label=p.kind==='nutrition'?'برنامه غذایی':'برنامه تمرینی';card.append(el('p',label,'w-count'),el('h2',p.title),el('p',p.coach_name+' ← '+p.athlete_name),el('p',p.club_name+' · نسخه '+p.revision+' · '+new Date(p.sent_at).toLocaleString('fa-IR',{timeZone:'Asia/Tehran'}),'w-muted'),link('مشاهده نسخه ارسال‌شده',(p.kind==='nutrition'?'nutrition-view.html':'workout-view.html')+'?id='+encodeURIComponent(p.id)));list.append(card)}else if(p.kind==='training')select.append(new Option(p.title+' · '+p.coach_name+' · '+new Date(p.sent_at).toLocaleDateString('fa-IR'),p.id))}more.hidden=!data.hasMore;if(page===2&&!data.deliveries.length)body.append(el('p','هنوز برنامه‌ای ارسال نشده است.'))}
 select.onchange=()=>{if(select.value)open(select.value);else{++loadVersion;stopTimer();body.replaceChildren()}};await load();const id=new URLSearchParams(location.search).get('id');if(id&&!log)await open(id);report(log?'گزارش نسخه‌های ارسال‌شده':'برنامه دلخواه را از فهرست انتخاب کنید؛ ویرایش آن فقط در اختیار مربی است.')}
async function init(value){if(started)return;started=true;user=value;const routes={coach:'coach-dashboard.html',athlete:'dashboard.html',manager:'admin.html',support:'support.html',secretary:'secretary.html'};document.getElementById('workout-back').href=routes[user.role]||'access-center.html';try{if(mode==='builder'){if(templateId){const saved=await api('/templates/'+encodeURIComponent(templateId));if(saved.archived)throw Error('program_archived');program=saved.program;revision=saved.revision}day=0;renderBuilder();report('روز شنبه · برنامه هفتگی شما')}else if(mode==='library')await library();else if(mode==='catalog'){await catalogUI(root);report('نام حرکات بین آموزش و برنامه تمرینی مشترک است.')}else await deliveries(mode==='log')}catch(e){report(e);root.append(btn('تلاش دوباره',()=>location.reload()))}}
window.addEventListener('mg:access-ready',e=>init(e.detail));if(window.MGCurrentUser)init(window.MGCurrentUser);
